export const categories = {
  health: 'Health___Fitness',
  education: 'education',
  fashion: 'fashion',
  miscellaneous: 'miscellaneous',
  travel: 'travel',
  science: 'science',
  automobile: 'automobile',
  world: 'world',
  entertainment: 'entertainment',
  startup: 'startup',
  technology: 'technology',
  sports: 'sports',
  politics: 'politics',
  business: 'business',
  national: 'national',
};
